### ISSUE TITLE
New Movies not being updated

### ISSUE THREAD

**Issue by jl94x4** [x1ao4/edition-manager-for-plex#3]
Flask server seems to be working, but not updating anything. Is there anything I need to configure to make this work?

```[2024-10-14 03:57:38] Successfully connected to server: SubZero
INFO:__main__:Successfully connected to server: SubZero
[2024-10-14 03:57:38] Starting webhook server for processing new movies...
INFO:__main__:Starting webhook server for processing new movies...
 * Serving Flask app 'edition-manager'
 * Debug mode: off```

**Comment by x1ao4** [comment]
In the Plex server settings, navigate to `Webhooks`, click on `Add Webhook`, and enter your Flask server address `http://Docker host IP address:8089` and `Save Changes`. (Non-Plex Pass subscribers do not need to fill this.)

or

In the Plex server settings, navigate to `Webhooks`, click on `Add Webhook`, and enter your Flask server address `http://IP address of the device running the script:8089` and `Save Changes`. (Non-Plex Pass subscribers do not need to fill this.)

Note: The `add editions for new movies` mode requires the server administrator account to be subscribed to Plex Pass in order to use.

**Comment by jl94x4** [comment]
Thanks!
